development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://gnvfbwayoopvis:792c9942fbe405d1cbf9c8c762cd903249a39b298fbc9a711da75e4ddcab60fb@ec2-54-235-64-195.compute-1.amazo
  channel_prefix: store_productio
